version: "3.9"

services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/www
  php:
    build: './php'
    volumes:
      - ./webroot:/www
  db:
    build: "./mariadb"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 45000:3306
    volumes:
      - ./dbstorage:/var/lib/mysql
      - ./mariadb/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - MARIADB_ROOT_PASSWORD=lbspasswordroot
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 45001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=25G
